# Generated by Django 4.0.4 on 2022-06-07 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idCarrito', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Carrito')),
            ],
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID categoría')),
                ('nombreCategoria', models.CharField(max_length=30, verbose_name='Nombre Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Cliente')),
                ('nombreCliente', models.CharField(max_length=30, verbose_name='Nombre Cliente')),
                ('apellidoCliente', models.CharField(max_length=30, verbose_name='Apellido Cliente')),
                ('correoCliente', models.CharField(max_length=420, verbose_name='Correo Cliente')),
                ('direccionCliente', models.CharField(max_length=420, verbose_name='Dirección Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Producto')),
                ('nombreProducto', models.CharField(max_length=30, verbose_name='Nombre Producto')),
                ('imagen', models.CharField(max_length=256)),
                ('precio', models.IntegerField(verbose_name='Precio Producto')),
                ('stock', models.IntegerField(verbose_name='Stock Producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='frontend.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to='frontend.carrito')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='frontend.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ch_productos', to='frontend.producto')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_productos', to='frontend.producto'),
        ),
    ]
